# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "2.5"
  - "2.6"
  - "2.7"
# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.1.4
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
# Tell it the things it will need to install when it boots
install:
 - pip install -r requirements.txt --use-mirrors
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
 - pip install -q -e . --use-mirrors
 - pip install pep8 --use-mirrors
 before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
script: python setup.py test